---
title: "Plotly & RMarkdown Course Project"
author: "Ellen Bayens"
date: "4-12-2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

## Weight and miles per gallon compared to number of cylinders

As we see in the plots, both weigth and miles per gallon are dependant of the number of cylinders.
The weight is directly dependant on the number of cylinder, but the miles per gallon is inversely proportional.  

```{r cars}
library(dplyr)
library(plotly)
mydata <- mtcars %>%
  mutate(cyl = as.factor(cyl))


plot_ly(mydata, y = ~mpg, color = ~cyl, type = "box") %>%
  layout(title = 'Miles per gallon compared to number of cylinders',
         xaxis = list(title = 'Number of cylinders'),
         yaxis = list(title = 'Miles per gallon'))
plot_ly(mydata, y = ~wt, color = ~cyl, type = "box", text = "Cylinders") %>%
  layout(title = "Weight compared to number of cylinders", 
         xaxis = list(title = "Number of cylinder"),
         yaxis = list(title = "Weight"))
```

